name: Publish binaries to GitHub release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-linux:
    name: Publish binary for Linux
    runs-on: ubuntu-latest
    container:
      # Use ubuntu-20.04 to compile with glibc 2.28
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install needed dependencies
      run: |
        apt-get update && apt-get install -y curl git
        apt-get install build-essential -y
    - name: clone meilisearch repo
      run: |
        git clone https://github.com/meilisearch/meilisearch
        cd meilisearch
        git fetch --tags
        git checkout ${{ github.event.release.tag_name }}
        cd ..
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --manifest-path=meilisearch/Cargo.toml --release --locked -p meilisearch -p meilitool --no-default-features --features "japanese"
    # No need to upload binaries for dry run (cron)
    - name: Upload binaries to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.7.0
      with:
        repo_token: ${{ secrets.GH_PAT }}
        file: meilisearch/target/release/meilisearch
        asset_name: meilisearch-linux-amd64
        tag: ${{ github.ref }}

  publish-macos-windows:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, windows-2022]
        include:
          - os: macos-12
            artifact_name: meilisearch
            asset_name: meilisearch-macos-amd64
          - os: windows-2022
            artifact_name: meilisearch.exe
            asset_name: meilisearch-windows-amd64.exe
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Checkout meilisearch repo
      uses: actions/checkout@v3
      with:
        repository: meilisearch/meilisearch
        path: meilisearch
        fetch-depth: 0
    - name: Checkout specific tag in meilisearch repo
      run: |
        cd meilisearch
        git fetch --tags
        git checkout ${{ github.event.release.tag_name }}
        cd ..
    - name: Build
      run: cargo build --manifest-path=meilisearch/Cargo.toml --release --locked -p meilisearch -p meilitool --no-default-features --features "japanese"
    # No need to upload binaries for dry run (cron)
    - name: Upload binaries to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.7.0
      with:
        repo_token: ${{ secrets.GH_PAT }}
        file: meilisearch/target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  publish-macos-apple-silicon:
    name: Publish binary for macOS silicon
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            asset_name: meilisearch-macos-apple-silicon
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout meilisearch repo
        uses: actions/checkout@v3
        with:
          repository: meilisearch/meilisearch
          path: meilisearch
          fetch-depth: 0
      - name: Checkout specific tag in meilisearch repo
        run: |
          cd meilisearch
          git fetch --tags
          git checkout ${{ github.event.release.tag_name }}
          cd ..
      - name: Installing Rust toolchain
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          profile: minimal
          target: ${{ matrix.target }}
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=meilisearch/Cargo.toml --release --target ${{ matrix.target }} -p meilisearch -p meilitool --no-default-features --features "japanese"
      - name: Upload the binary to release
        # No need to upload binaries for dry run (cron)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: meilisearch/target/${{ matrix.target }}/release/meilisearch
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

  publish-aarch64:
    name: Publish binary for aarch64
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    container:
      # Use ubuntu-20.04 to compile with glibc 2.28
      image: ubuntu:20.04
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            asset_name: meilisearch-linux-aarch64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install needed dependencies
        run: |
          apt-get update -y && apt upgrade -y
          apt-get install -y curl build-essential gcc-aarch64-linux-gnu git
      - name: clone meilisearch repo
        run: |
          git clone https://github.com/meilisearch/meilisearch
          cd meilisearch
          git fetch --tags
          git checkout ${{ github.event.release.tag_name }}
          cd ..
      - name: Set up Docker for cross compilation
        run: |
          apt-get install -y curl apt-transport-https ca-certificates software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt-get update -y && apt-get install -y docker-ce
      - name: Installing Rust toolchain
      - uses: dtolnay/rust-toolchain@1.79
      - uses: Swatinem/rust-cache@v2
        with:
          profile: minimal
          target: ${{ matrix.target }}
      - name: Configure target aarch64 GNU
        ## Environment variable is not passed using env:
        ## LD gold won't work with MUSL
        # env:
        #   JEMALLOC_SYS_WITH_LG_PAGE: 16
        #   RUSTFLAGS: '-Clink-arg=-fuse-ld=gold'
        run: |
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config
          echo 'JEMALLOC_SYS_WITH_LG_PAGE=16' >> $GITHUB_ENV
      - name: Install a default toolchain that will be used to build cargo cross
        run: |
          rustup default stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --manifest-path=meilisearch/Cargo.toml --release --target ${{ matrix.target }} -p meilisearch -p meilitool --no-default-features --features "japanese"
        env:
          CROSS_DOCKER_IN_DOCKER: true
      - name: List target output files
        run: ls -lR ./meilisearch/target
      - name: Upload the binary to release
        # No need to upload binaries for dry run (cron)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: meilisearch/target/${{ matrix.target }}/release/meilisearch
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
